const slidesData = {
    "folder":"img",
    "files":[
        "download (10).png",
        "download (11).png",
        "download (12).png",
        "download (13).png",
        "download (14).png",
        "download (15).png",
        "download (16).png",
        "download (17).png",
        "download (18).png",
        "download (19).png",
        "download (1).png",
        "download(1).png",
        "download (20).png",
        "download (21).png",
        "download (22).png",
        "download (23).png",
        "download (2).png",
        "download (3).png",
        "download (4).png",
        "download (5).png",
        "download (6).png",
        "download (7).png",
        "download (8).png",
        "download (9).png",
        "download.png",
        "with_normal_funct_1.png",
        "with_normal_funct_2.png",
        "with_normal_funct_3.png",
        "with_normal_funct_4.png",
        "with_normal_funct_5.png"
    ]
}